import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Navbar from './navbar';
import Footer from './footer';

export default function Layout({ children }) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/daisyui@2.40.1/dist/full.css" rel="stylesheet" type="text/css" />
                <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2/dist/tailwind.min.css" rel="stylesheet" type="text/css" />
            </Head>

            <header>
                <Navbar></Navbar>
            </header>

            <main className="min-h-screen container bg-red-800">
                { children }
            </main>

            <footer className={styles.footer}>
                <Footer></Footer>
            </footer>
        </div>
    );
}